### ISSUE TITLE
EPIC: Use OOTB apps in the ATs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-acceptance-tests#11]
Sources:
- http
- jdbc
- rabbit

Processors:
- splitter
- transform

Sink:
- jdbc
- rabbit

- [x] Create end to end AT for http | splitter | log on PCF
- [x] Create end to end AT for http | transform | log on PCF
- [x] Create end to end AT for jdbc | log on PCF

**Comment by sabbyanandan** [comment]
Verify SCDF email distribution is configured in the CI plans. Also, verify ops-channel in slack is configured correctly.

**Comment by sabbyanandan** [comment]
The sope of this epic is complete.
